services:
  task-manager:
    container_name: task-manager
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      - CONFIG_PATH=/app/internal/config.yaml
    ports:
      - "8080:8080"
    networks:
      - backend

  database:
    image: postgres:15-alpine
    container_name: task-database
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_PASSWORD: taskpass
      POSTGRES_USER: taskuser
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - /home/kirill/GolandProjects/task-manager-go/internal/metrics/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend
    depends_on:
      - task-manager

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - prometheus
volumes:
  postgres_data:

networks:
  backend: