// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "task-manager-go/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// TaskService is an autogenerated mock type for the TaskService type
type TaskService struct {
	mock.Mock
}

// Create provides a mock function with given fields: input
func (_m *TaskService) Create(input models.CreateTaskInput) (*models.Task, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(models.CreateTaskInput) (*models.Task, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(models.CreateTaskInput) *models.Task); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(models.CreateTaskInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *TaskService) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *TaskService) GetAll() ([]models.Task, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Task, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Task); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *TaskService) GetByID(id int) (*models.Task, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Task, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Task); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, input
func (_m *TaskService) Update(id int, input models.UpdateTaskInput) (*models.Task, error) {
	ret := _m.Called(id, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(int, models.UpdateTaskInput) (*models.Task, error)); ok {
		return rf(id, input)
	}
	if rf, ok := ret.Get(0).(func(int, models.UpdateTaskInput) *models.Task); ok {
		r0 = rf(id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(int, models.UpdateTaskInput) error); ok {
		r1 = rf(id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskService creates a new instance of TaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskService {
	mock := &TaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
